name: CI - NullTrace

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“… Checkout code
      uses: actions/checkout@v4

    - name: ðŸš€ Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: ðŸšš Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest

    - name: ðŸ”§ Run built-in NullTrace test
      run: |
        python3 -m nulltrace.NullTrace --test

    - name: ðŸ“Š Run pytest unit tests
      run: |
        pytest tests/
